<!-- Fin Main -->
</main>

<footer class="d-flex flex-wrap justify-content-center align-items-center py-3 my-4 border-top">
    <div class="align-items-center">
        <span class="text-muted">2023 TPE TUDAI, UNICEN</span>
    </div>
</footer>
    
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
    $(".pedido-row").on("click", "#detalle-btn", function() {
        $(this).closest("tr").next(".detalle-row").toggle();
    });
});
//    document.addEventListener('DOMContentLoaded', function() {
//    const rows = document.querySelectorAll('#table-row');

//    rows.forEach(row => {
//       row.addEventListener('click', function() {
//          const detailsRow = this.nextElementSibling;
//          detailsRow.style.display = (detailsRow.style.display === 'none' || detailsRow.style.display === '') ? 'table-row' : 'none';
//       });
//    });
// });

</script>

</body>
</html>