<?php require_once 'templates/headerAdmin.phtml'; ?>

<br>

<h2 style="margin-left: 30px;">Ingrese sus pedidos</h2>

<br>

<div class="container-home-admin d-flex justify-content-center align-items-start" style="min-height: 100vh;">

<!-- CARGA DE PEDIDOS VISTA ADMIN -->

  <div class="conteiner-form mx-auto" style="width: 30vw;">
    <form action="agregar-pedido" method="POST" style="width: 30vw;">
      <div class="mb-3">
        <label for="" class="form-label">Nombre del cliente</label>
        <input name="nombre-cliente" class="form-control mr-sm-2" type="search" placeholder="Ingrese el nombre del cliente" aria-label="Search">
      </div>
      <div class="mb-3">
        <label for="" class="form-label">Ciudad</label>
        <input name="ciudad-cliente" class="form-control mr-sm-2" type="search" placeholder="Ingrese la ciudad del cliente" aria-label="Search">
      </div>
      <div class="mb-3">
        <label for="" class="form-label">Dirección</label>
        <input name="direccion-cliente" class="form-control mr-sm-2" type="search" placeholder="Ingrese la dirección del cliente" aria-label="Search">
      </div>
      <div class="mb-3">
        <label for="" class="form-label">Código postal</label>
        <input name="codigo-postal" class="form-control mr-sm-2" type="search" placeholder="Ingrese el código postal del cliente" aria-label="Search">
      </div>
      <div class="mb-3">
        <label for="" class="form-label">Fecha de envio</label>
        <input name="fecha-envio" class="form-control mr-sm-2" type="datetime-local" placeholder="Ingrese la fecha del envio" aria-label="Search">
      </div>
      <div class="mb-3">
        <label for="" class="form-label">Producto</label>
        <input name="producto" class="form-control mr-sm-2" type="search" placeholder="Ingrese el producto" aria-label="Search">
      </div>
      <div class="mb-3">
        <label for="" class="form-label">Cantidad</label>
        <input name="cantidad" class="form-control mr-sm-2" type="search" placeholder="Ingrese la cantidad del producto" aria-label="Search">
      </div>
      <div class="mb-3">
        <label for="" class="form-label">Total a pagar</label>
        <input name="total-pagar" class="form-control mr-sm-2" type="search" placeholder="Ingrese el total del pedido" aria-label="Search">
      </div>
      <div class="mb-3">
        <label for="" class="form-label">Tipo de enivo</label>
        <select name="tipo-envio" class="form-control mr-sm-2" type="search" placeholder="Seleccione una categoría" aria-label="Search">
          <?php foreach($tipoEnvios as $tipoEnvio): ?>
            <option value="<?= $tipoEnvio->tipoEnvioId ?>"><?= $tipoEnvio->nombreEnvio ?></option>
          <?php endforeach; ?>
        </select>

      </div>
      <div class="mb-3">
        <label for="" class="form-label">Repartidor</label>
        <select name="repartidor-asignado" class="form-control mr-sm-2" type="search" placeholder="Seleccione un repartidor" aria-label="Search">
          <?php foreach($repartidores as $repartidor): ?>
            <option value="<?= $repartidor->repartidorId ?>"><?= $repartidor->nombreCompleto ?></option>
          <?php endforeach; ?>
        </select>
      </div>


      <button type="submit" class="btn btn-primary">Asignar</button>
    </form>
  </div>

<!-- TABLA DE PEIDOS VISTA ADMIN -->

  <div class="container-tabla mx-auto">

  <!-- Buscador de pedidos -->
    <div class="container-nav-form">
        <form class="form-inline my-4 my-lg-2" style="display: flex; flex-direction: row;">
            <input class="form-control mr-sm-2" style="width: 60%; margin-right:20px;" type="search" placeholder="Buscar pedido" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
        </form>
    </div>
  <!-- Tabla de pedidos -->
    <div class="container-tabla mx-auto" style="width: 60vw; border: 1px solid #ccc; border-radius: 10px;">
      <table id="table" class="table table-hover align-middle">
        <thead>
            <tr>
            <th scope="col" class="text-center">#</th>
            <th scope="col" class="text-center">Cliente</th>
            <th scope="col" class="text-center">Dirección</th>
            <th scope="col" class="text-center">Repartidor</th>
            <th scope="col" class="text-center">Estado del pedido</th>
            <th scope="col" class="text-center">Editar</th>
            </tr>
        </thead>
        <tbody>
          <?php foreach($pedidos as $pedido): ?>
            <tr class="pedido-row">
            <th scope="row" class="text-center"><?= $pedido->numeroPedido ?></th>
              <td class="text-center"><?= $pedido->nombreCliente ?></td>
              <td class="text-center"><?= $pedido->calle ?></td>
              <td class="text-center"><?= $pedido->nombre_repartidor ?></td>
              <td class="text-center"><a style="<?= $pedido->estadoPedido == 1 ? 'background-color: #B7F4CD;' : 'background-color: #F6CEC8;' ?> padding: 5px 15px 5px 15px; border-radius: 50px; text-decoration: none; color: black;"><?= $pedido->estadoPedido == 1 ? 'Entregado' : 'Sin entregar' ?></a></td>
              <td class="text-center">
                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Editar
                  </button>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="modificar-pedido">Editar</a></li>
                    <li><a class="dropdown-item" id="detalle-btn" style="cursor: pointer;">Detalle</a></li>
                    <li><a class="dropdown-item" href="eliminar-pedido/<?= $pedido->numeroPedido ?>">Borrar</a></li>
                  </ul>
                </div>
              </td>
            </tr>
            <!-- Prueba de despligue de informacion -->
            <tr class="detalle-row" style="display: none;">
                <td colspan="6" class="text-center">
                <b>Tipo de envio:</b> <?= $pedido->nombreEnvio ?> | <b>Producto:</b> <?= $pedido->producto ?> | <b>Cantidad:</b> <?= $pedido->cantidad ?> | <b>Total a pagar:</b> $<?= $pedido->total?> | <b>Hora de entrega:</b> <?= $pedido->fechaEnvio ?>
                </td>
            </tr>
            <!-- Fin de prueba -->
          <?php endforeach; ?>
          
        </tbody>
      </table>
    </div>
  </div>
</div>

<br>

<br>

<br>


<?php require_once 'templates/footer.phtml'; ?>


<!-- class="table-details" style="width: 100%; display: none; width: 100%; overflow: hidden; background-color: #f9f9f9; color: #333; padding: 10px;" -->