
<?php require_once 'templates/header.phtml' ?>
    
    <div class="container-index" style="display: flex; flex-direction: row; justify-content: center; align-items: center; height:85vh;">
        <div class="lateral-izq" style="width: 50%; height:75vh; display: flex; justify-content: center; align-items: center; background-color: #f2f2f2; border-radius: 15px; margin-left:25px">
            <h3 style="text-align: center; padding: 20px;">TPE WEB</h3>
        </div>
        <div class="lateral-der" style="display: flex; justify-content: center; align-items: center; text-align: center; padding: 20px; width: 50%; height: 75vh;">
            <a href="acceso-publico" class="btn btn-primary mt-2" style="margin-right: 25px;">Acceso Ryders</a>
            <a href="login" class="btn btn-primary mt-2">Acceso Empresa</a>
        </div>
    </div>

<?php require_once 'templates/footer.phtml' ?>
