<?php require 'templates/header.phtml' ?>
<div class="container-index" style="display: flex; flex-direction: row; justify-content: center; align-items: center; height:85vh;">
        <div class="lateral-izq" style="width: 50%; height:75vh; display: flex; justify-content: center; align-items: center; background-color: #f2f2f2; border-radius: 15px; margin-left:25px">
            <h3 style="text-align: center; padding: 20px;">TPE WEB</h3>
        </div>
        <div class="lateral-der" style="display: flex; justify-content: center; align-items: center; text-align: center; padding: 20px; width: 50%; height: 75vh;">
            
        <div style="width: 50%;">
            <form method="POST" action="logear">
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" style="margin-bottom:20px;" class="form-control" id="username" name="username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" required class="form-control" id="password" name="password">
                </div>

                <?php if ($error) : ?>
                    <div class='alert alert-danger' role='alert'>
                        <?= $error ?>
                    </div> 
                <?php endif ?>
            
                <button type="submit" class="btn btn-primary mt-3">Entrar</button>
            </form>
            <!-- <a href="registro" class="btn btn-primary mt-3">Registro</a> -->
        </div>

        </div>
    </div>

<?php require 'templates/footer.phtml' ?>
